### ISSUE TITLE
No Miso/Mosi/SS Port

### ISSUE THREAD

**Issue by SoerenBusse** [leokoppel/GP22#1]
Hi,
I have a GP22. Now I want to connect them to the arduino. But I dont find the MISO/MOSI/SS Port in the datasheet p. 15: 
http://www.etracker.de/lnkcnt.php?et=UKbtw3&url=http://www.acam.de/fileadmin/Download/pdf/TDC/English/DB_GP22_en.pdf&lnkname=DB_GP22_en

What ports should I use? SO and SI?

**Comment by leokoppel** [comment]
Yes. SO and SI are equivalent to MISO and MOSI.
